baseURL: http://example.org/
languageCode: es/es
title: empresa_ACMe
theme: Basico
author: 
  facebook: "https://facebook.com/example" 
  twitter: "https://twitter.com/example" 
  email: "contact@example.org" 
  name: "Acme Corporation" 
  location: Zaragoza
  phone: (999) 999-9999 
  hours: "**Lunes-Viernes** 9:00AM - 6:00PM" 

menu:
  main: 
    - identifier:  inicio
      name: inicio
      url: /inicio
      weight: 100  
    - identifier: about 
      name: about
      url: /about 
      weight: 100 
    - identifier: contact
      name: Contacto 
      url: /contacto 
      weight: 200 
    - identifier: curriculum
      name: curriculum
      url: /curriculum 
      weight: 300 
    - identifier: tiendas
      url: /tiendas
      name: tiendas 
      weight: 400 
    - identifier: viaje
      url: /viaje
      name: viaje 
      weight: 500 
    - identifier: blog
      url: /blog
      name: blog
      weight: 600 
    
params: 
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Acme Corporation. Todos los derechos reservados."
  footer:
  - title: About
    content: >
      Acme Corporation is the world's leading
      manufacturer of digital shapes. From squares and
      circles to triangles and hexagons, we have it
      all. Browse through our collection of various
      forms with different thicknesses and line styles.
      We shape the world. You live in it.      


  - title: Publicaciones recientes
    recents: blog
    recentCount: 7

  - title: Contact Us
    contact: true